test-centos7:
  image: ansible/ansible:centos7
  before_script:
    - python -V
    - pip install ansible ansible-lint
    - ansible --version
  script:
    - cd tests
    - ansible-lint main.yml
    - ansible-playbook --verbose --diff main.yml
  after_script:
    - sudo cat /etc/ssh/sshd_config
