test-centos7:
  image: ansible/ansible:centos6
  before_script:
    - python -V
    - pip install ansible ansible-lint
    - ansible --version
    - sudo cat /etc/ssh/sshd_config
  script:
    - cd tests
    - ansible-lint main.yml
    - ansible-playbook --verbose --diff main.yml
  after_script:
    - sudo cat /etc/ssh/sshd_config
    - sudo diff -u /etc/ssh/sshd_config.orig /etc/ssh/sshd_config
