version: 2.1

jobs:
  build:
    docker:
      - image: 'centos/systemd'
    working_directory: ~/sshd/
    steps:
      - run: sudo yum install -y https://centos7.iuscommunity.org/ius-release.rpm
      - run: sudo yum install python36u python36u-libs python36u-devel python36u-pip
      - run: sudo pip3.6 install ansible ansible-lint
      - checkout
      - run:
          command: ansible-playbook main.yml
          working_directory: ~/sshd/tests/

workflows:
  my-workflow:
    jobs:
      - build
