version: 2.1

jobs:
  build:
    docker:
      - image: 'centos/systemd'
    working_directory: ~/sshd/
    steps:
      - run:
          command: |
            yum install -y epel-release
            yum install -y python-pip --enablerepo=epel
            pip install ansible ansible-lint
      - checkout
      - run:
          command: ansible-playbook main.yml
          working_directory: ~/sshd/tests/

workflows:
  my-workflow:
    jobs:
      - build
