version: 2.1
orbs:
  ansible-ssh: orbss/ansible-ssh@0.7.4

jobs:
  build:
    docker:
      - image: 'tomonorimatsumura/centos7-ansible:yum'
    steps:
      - ansible-ssh/ansible-playbook

workflows:
  my-workflow:
    jobs:
      - build
