version: 2.1
orbs:
  ansible-ssh: orbss/ansible-ssh@0.7.4

jobs:
  build:
    docker:
      - image: 'ansible/ansible:centos7'
    working_directory: ~/sshd/
    steps:
      - checkout
      - run: sudo pip install ansible ansible-lint
      - run:
          name: build
          command: ansible-playbook main.yml
          working_directory: ~/sshd/tests/
workflows:
  my-workflow:
    jobs:
      - build
