version: 2.1
orbs:
  ansible-ssh: orbss/ansible-ssh@0.7.4

jobs:
  build:
    docker:
      - image: 'ansible/ansible:centos7'
    working_directory: ~/project/tests/
    steps:
      - run: sudo pip install ansible ansible-lint
      - run: ansible-playbook test.yml
workflows:
  my-workflow:
    jobs:
      - build
